Modifications
-------------

First it is recommended to update the software you are packaging to its newest upstream version. If it already is at the latest version, increment the release number. Don't forget to add a ``%changelog`` entry as well.

.. note::

    In this document you will encounter lot of RPM macros. You can look up many of the Python macros in the `Python packaging guidelines`_ (click the **Expand button** on the right side).

.. _`Python packaging guidelines`: https://fedoraproject.org/wiki/Packaging:Python#Macros
